apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: flask-app
        image: amel91/myimage
        ports:
        - containerPort: 5000




apiVersion: v1
kind: Service
metadata:
  name: myimage
spec:
  selector:
    app: myimage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer